### ISSUE TITLE
unable to start ROM

### ISSUE THREAD

**Issue by EnricoGiordano1992** [haofanurusai/VerilogBoy-Zedboard#1]
Hello, I am trying your project but, when I recompile it, in the output I see a centered green screen. 
I have added the missing tobudx.coe file converted from the Tobu ROM (in the block memory Cart_ram_inst -> tobu: CartTobu).
For the recompilation, are additional steps required?

**Comment by haofanurusai** [comment]
Sorry for my late reply. Did you success?

**Comment by EnricoGiordano1992** [comment]
Yes thanks, I was able to recompile it cleaning the output product
